# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Make envfile
      run: |
        touch .env
        echo TOKEN=${{ secrets.TOKEN }} >> .env
        echo SHEETS_API_KEY=${{ secrets.SHEETS_API_KEY }} >> .env
    - name: Restart the bot
      run: pm2 restart xpose-bot
